import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import AuthProvider from "@/components/AuthProvider";
import TopMenu from "@/components/layout/TopMenu";
import { WishlistProvider } from "@/context/WishlistContext";
import { CartProvider } from "@/context/CartContext";
import BottomBar from "@/components/layout/BottomBar";
import NavigationLoading from "@/components/ui/NavigationLoading";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <AuthProvider>
          <WishlistProvider>
            <CartProvider>
              <NavigationLoading>
                <TopMenu />
                {children}
                <BottomBar />
              </NavigationLoading>
              <Toaster />
            </CartProvider>
          </WishlistProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
